spec:
  template:
    spec:
      containers:
      - name: alertmanager
        livenessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 6
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "256Mi"
