apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-status-config
data:
  status.conf: |
    server {
        listen 8081;
        location /status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
