apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ha
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-ha
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
